import {ArrowLink,Eyebrow} from '@/components/ui';import {EditorialImage,Portrait} from '@/components/portrait';import {insights,programs} from '@/lib/data';
export default function Home(){const schema={"@context":"https://schema.org","@type":"Person",name:"Bogdan Vizitiu",url:"https://bogdanvizitiu.ro",jobTitle:"Executive educator and strategic advisor",knowsAbout:["Leadership","Strategy","Organizational development","Decision making"]};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<section className="hero shell"><div className="hero-grid"><div className="hero-copy"><Eyebrow>Bogdan Vizitiu</Eyebrow><h1>Leadership.<br/>Strategy.<br/>Growth.</h1><p className="lead">Practical thinking for people who lead, build and make decisions.</p><div className="actions"><ArrowLink href="/programs">Explore programs</ArrowLink><a className="text-link" href="/about">About Bogdan</a></div></div><Portrait/></div></section>
<section className="areas shell"><Eyebrow>Selected areas</Eyebrow><div className="area-grid">{[['01','Leadership','Lead with clarity when context, expectations and stakes keep shifting.'],['02','Strategy','Turn ambition into deliberate choices people can understand.'],['03','Execution','Build the focus and operating discipline that move work forward.']].map(a=><article className="area" key={a[0]}><span className="num">{a[0]}</span><h3>{a[1]}</h3><p>{a[2]}</p></article>)}</div></section>
<section className="position shell"><div className="position-copy"><p className="quote">“Good decisions require better thinking.”</p><p>Bogdan works at the intersection of leadership, strategy, organizational development and execution, helping people turn complexity into clearer decisions and practical action.</p><ArrowLink href="/about">About Bogdan</ArrowLink></div><Portrait/></section>
<section className="programs shell"><div className="section-head"><div><Eyebrow>Learning experiences</Eyebrow><h2 className="section-title">Programs</h2></div><p>Open learning experiences for professionals, leaders and organizations.</p></div>{programs.map((p,i)=><article className="program-row" key={p.slug}><span>0{i+1}</span><h3>{p.title}</h3><p>{p.description}</p><ArrowLink href={`/programs/${p.slug}`}>View program</ArrowLink></article>)}</section>
<section className="dark"><div className="shell corporate-grid"><div className="corporate-title"><Eyebrow>For organizations</Eyebrow><h2>Learning designed around<br/>the organization.</h2></div><div className="corporate-copy"><p>Custom workshops, leadership programs and strategic learning interventions developed around real organizational challenges.</p><ArrowLink href="/corporate">Corporate programs</ArrowLink></div><div className="domain-list"><div><span>01</span>Leadership development</div><div><span>02</span>Team effectiveness</div><div><span>03</span>Strategy & execution</div></div><EditorialImage kind="workshop" label="Workshop photography placeholder"/></div></section>
<section className="shell experience-grid"><div><Eyebrow>Track record</Eyebrow><h2 className="section-title">Selected experience</h2><p className="placeholder-warning">Placeholder data — pending verification</p></div><div className="org-list">{['Organization 01','Executive program 02','Industry partner 03','Public institution 04','Leadership cohort 05','Strategic project 06'].map(x=><div key={x}>{x}</div>)}</div></section>
<section className="insights shell"><div className="section-head"><div><Eyebrow>Thinking in public</Eyebrow><h2 className="section-title">Insights</h2></div><ArrowLink href="/insights">View all insights</ArrowLink></div><div className="insight-grid"><article className="feature-insight"><EditorialImage kind="insight" label="Featured insight photography placeholder"/><div className="story-meta"><span className="category">{insights[0].category}</span><span>6 min read</span></div><h3>{insights[0].title}</h3><p>{insights[0].excerpt}</p><ArrowLink href={`/insights/${insights[0].slug}`}>Read article</ArrowLink></article><div className="secondary-stories">{insights.slice(1).map((x,i)=><article className="insight-card" key={x.slug}><span className="story-number">0{i+2}</span><span className="category">{x.category}</span><h3>{x.title}</h3><p>{x.excerpt}</p><ArrowLink href={`/insights/${x.slug}`}>Read article</ArrowLink></article>)}</div></div></section>
<section className="speaking shell"><Portrait event/><div><Eyebrow>Speaking</Eyebrow><h2>Ideas worth discussing.</h2><p>Keynotes, workshops, panels and executive sessions that make complex ideas clear, relevant and useful in the room.</p><ArrowLink href="/speaking">Speaking & workshops</ArrowLink></div></section>
<section className="newsletter shell"><h2>Notes on leadership, organizations and better decisions.</h2><div className="newsletter-side"><p>Occasional ideas, frameworks and observations from Bogdan. No noise, only useful thinking.</p><ArrowLink href="#">Follow on LinkedIn</ArrowLink><form className="newsletter-form"><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" placeholder="Email address"/><button type="submit">Subscribe →</button></form></div></section>
<section className="contact-band shell"><h2>Let’s build something useful.</h2><div className="contact-bottom"><div className="contact-options">Corporate programs · Speaking<br/>Partnerships · Open courses</div><ArrowLink href="/contact">Get in touch</ArrowLink></div></section></>}
